### ISSUE TITLE
[TIP] 커밋 메시지 로그

### ISSUE THREAD

**Issue by RyuK-H** [anxiubin/TIL#1]
단순한 튜토리얼 프로젝트라도 커밋 로그를 잘 작성하면 좋을 것 같아여, 지금도 부족하진 않고 정답은 없지만(현업에선 팀바이팀입니다.), 저는 pandas 프로젝트 커밋 방식을 따라한답니다.

```
ENH: (Enhancement) 개선하거나 신기능 추가
BUG: 버그 수정
DOC: (Documentation) 문서화 관련된 작업
TST: (Test) 새로운 유닛테스트를 추가하거나 기존 테스트를 수정
BLD: (Build) 빌드 프로세스 관련 코드 혹은 스크립트를 수정
PERF: (Performance) 계산 속도의 개선과 관련된 작업
CLN: (Cleanup) 코드를 정리하거나 리팩토링한 작업
```

저도 `커밋은 자주 할 수록 좋다.`라는 입장을 고수 하고 있지만, 너무 무의미한 커밋은 개발자들이 많아질 경우 혼란을 가지고 올 수도 있어요. 자신만의 커밋 규칙을 정해보는 것도 분명 큰 도움이 될 것입니다.

저 같은 경우에는 패키지가 추가 될 때, 해당 패키지만 커밋 하고 기술 구현 까지 작은 Goal을 설정하고 그 골을 달성할 때마다 커밋을 하는 방식을 선호해요.

출처 : [pandas 가이드라인](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html)

**Comment by anxiubin** [comment]
> 단순한 튜토리얼 프로젝트라도 커밋 로그를 잘 작성하면 좋을 것 같아여, 지금도 부족하진 않고 정답은 없지만(현업에선 팀바이팀입니다.), 저는 pandas 프로젝트 커밋 방식을 따라한답니다.
> 
> ```
> ENH: (Enhancement) 개선하거나 신기능 추가
> BUG: 버그 수정
> DOC: (Documentation) 문서화 관련된 작업
> TST: (Test) 새로운 유닛테스트를 추가하거나 기존 테스트를 수정
> BLD: (Build) 빌드 프로세스 관련 코드 혹은 스크립트를 수정
> PERF: (Performance) 계산 속도의 개선과 관련된 작업
> CLN: (Cleanup) 코드를 정리하거나 리팩토링한 작업
> ```
> 
> 저도 `커밋은 자주 할 수록 좋다.`라는 입장을 고수 하고 있지만, 너무 무의미한 커밋은 개발자들이 많아질 경우 혼란을 가지고 올 수도 있어요. 자신만의 커밋 규칙을 정해보는 것도 분명 큰 도움이 될 것입니다.
> 
> 저 같은 경우에는 패키지가 추가 될 때, 해당 패키지만 커밋 하고 기술 구현 까지 작은 Goal을 설정하고 그 골을 달성할 때마다 커밋을 하는 방식을 선호해요.
> 
> 출처 : [pandas 가이드라인](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html)

이런 커밋 가이드가 필요하다고는 생각했는데, 제안해주셔서 감사합니다!
오늘 바로 실천하도록 할게요 :-)
